### ISSUE TITLE
Link failures

### ISSUE THREAD

**Issue by skeuchel** [haskell-haskey/xxhash-ffi#2]
The `xxhash` and `xxhash-ffi` packages both compile and expose the xxhash C library which can lead to link failures depending on the toolchain used. Here is an example of compiling and linking the benchmark with `ghc-8.0.2`, `cabal-install-2.0.0.1`, `Cabal-2.0.1.1`, `gcc-8.2.0`, `binutils-2.31.1 (ld.bfd)` in which the symbols from both packages clash.

```
Linking <<BUILD>>/xxhash-ffi-bench/xxhash-ffi-bench ...
/usr/bin/ld: <<BUILD>>/libHSxxhash-ffi-0.2.0.0-inplace.a(xxhash.o): in function `XXH32':
xxhash.c:(.text+0x10): multiple definition of `XXH32'; <<STORE>>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o):xxhash.c:(.text+0x0): first defined here
/usr/bin/ld: <<BUILD>>/libHSxxhash-ffi-0.2.0.0-inplace.a(xxhash.o): in function `XXH32_update':
xxhash.c:(.text+0x1e0): multiple definition of `XXH32_update'; <<STORE>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o):xxhash.c:(.text+0x1b0): first defined here
/usr/bin/ld: <<BUILD>>/libHSxxhash-ffi-0.2.0.0-inplace.a(xxhash.o): in function `XXH32_digest':
xxhash.c:(.text+0x3b0): multiple definition of `XXH32_digest'; <<STORE>>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o):xxhash.c:(.text+0x440): first defined here
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build bench:xxhash-ffi-bench from xxhash-ffi-0.2.0.0.
```

Also starting with GHC-8.4 the runtime system includes a copy of xxhash which adds another clash:

```
Linking <<BUILD>>/xxhash-ffi-bench/xxhash-ffi-bench ...
/usr/bin/ld.gold: error: /opt/ghc/8.4.4/lib/ghc-8.4.4/rts/libHSrts_thr.a(xxhash.thr_o): multiple definition of 'XXH32'
/usr/bin/ld.gold: <<STORE>>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o): previous definition here
/usr/bin/ld.gold: error: /opt/ghc/8.4.4/lib/ghc-8.4.4/rts/libHSrts_thr.a(xxhash.thr_o): multiple definition of 'XXH32_update'
/usr/bin/ld.gold: <<STORE>>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o): previous definition here
/usr/bin/ld.gold: error: /opt/ghc/8.4.4/lib/ghc-8.4.4/rts/libHSrts_thr.a(xxhash.thr_o): multiple definition of 'XXH32_digest'
/usr/bin/ld.gold: <<STORE>>/xxhash-0.0.2-<<HASH>>/lib/libHSxxhash-0.0.2-<<HASH>>.a(xxhash.o): previous definition here
collect2: error: ld returned 1 exit status
```

**Comment by skeuchel** [comment]
We should use the 'namespace emulation' that the C library provides to rename the symbols. That unfortunately won't fix the benchmark with GHC>=8.4. Probably we should just drop the xxhash dep.

I'm also wondering if we could link against a system lib (libxxhash is in Ubuntu-18.10 and will be in Debian 10) or if that's completely impossible now. Linking with duplicates is a bit obscure.

**Comment by hverr** [comment]
> Probably we should just drop the xxhash dep.

Agree, benchmarking is nice, linking is more important

> I'm also wondering if we could link against a system lib (libxxhash is in Ubuntu-18.10 and will be in Debian 10) or if that's completely impossible now. Linking with duplicates is a bit obscure.

Complicated approach

I vote just prefixing all C functions with `hs_xxhash_ffi_` or something similar.

**Comment by Bodigrim** [comment]
Modern GHCs seems to improve their linking story; at least CI no longer suffers from name clashes.

I tried to set `XXH_NAMESPACE`, but it actually broke linking :)
